# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mr4bwD2__VybVY2MbyeqGcPlJxEwmads
"""

from flask import Flask, render_template
import openai

app = Flask(__name__)

# Set your OpenAI API key
openai.api_key = "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"

# Define a function that takes in a user prompt and returns an OpenAI-generated response
def generate_response(prompt):
    response = openai.Completion.create(
        engine="text-davinci-002",
        prompt=prompt,
        max_tokens=60,
        temperature=0.5,
    )
    return response.choices[0].text

# Define a route for your home page
@app.route('/')
def home():
    return render_template('index.html')

# Define a route for your chatbot API
@app.route('/api/chatbot/<prompt>')
def chatbot(prompt):
    response = generate_response(prompt)
    return response

if __name__ == '__main__':
    app.run(debug=True)