# -*- coding: utf-8 -*-
"""openai_v3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NZxwwg8iLP72zQeb6OueX_ucL2pFx3zE
"""
// chatbot with openai

!pip install openai

# import libraries
from openai.api_resources import model
import os
import openai

# Set your OpenAI API key
openai.api_key = "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"

# Define a function that takes in a user prompt and returns an OpenAI-generated response
def generate_response(prompt):
    response = openai.Completion.create(
        engine="text-davinci-002",
        prompt=prompt,
        max_tokens=60,
        temperature=0.5,
    )
    return response.choices[0].text

# Define a function that prompts the user for input and returns a response generated by the chatbot
def chat():
    print("Hi! I'm a chatbot. How can I help you today?")
    while True:
        prompt = input("You: ")
        if prompt.lower() in ["bye", "goodbye", "exit", "quit"]:
            print("Chatbot: Goodbye!")
            break
        response = generate_response(prompt)
        print("Chatbot:", response)

# Call the chat function to start the chatbot
chat()